Find average fare for rides between the Loop and each census tract.

Strategy:

Step 1:
For each chunk of the data, calculate
1. total number of rides to/from each census tract to the Loop
2. total fare for those rides
3. total of fare${^2}$ for those rides

I can recover the mean and standard deviation from these.

Step 2:
Do the same thing, but filter the rides to make sure that the fares are within 3 sigma from the mean.

Step 3:
Another iteration. This should yield relatively nice answers.

This was done using Hadoop for the full dataset.

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [56]:
df_avg = pd.read_csv('GetAvg/stats_3.csv')

In [57]:
df_avg

    census_tract        avg       std
0    17031071500   9.857036  1.560321
1    17031080100   8.632758  1.418982
2    17031080202   8.290581  1.299264
3    17031081000   7.501670  1.273995
4    17031081100   7.691097  1.287136
5    17031081201   7.613701  1.406324
6    17031081202   8.042223  1.438961
7    17031081300   7.680067  1.498691
8    17031081401   7.160339  1.396197
9    17031081402   7.408777  1.472040
10   17031081403   6.532011  1.368273
11   17031081500   6.497953  1.358428
12   17031081600   6.197119  1.245466
13   17031081700   6.129961  1.214652
14   17031081800   6.627601  1.317123
15   17031280100   6.142162  1.171677
16   17031281900   6.162483  1.251711
17   17031320100   5.782515  1.609121
18   17031320400   5.482976  1.522101
19   17031320600   6.173929  1.795256
20   17031330100   8.454182  1.964130
21   17031833100   7.221796  1.457004
22   17031839100   5.599916  1.456856
23   17031980000  40.009800  4.366554
24   17031980100  28.536748  3.431448